### ISSUE TITLE
BLOCKED SITE ALERT

### ISSUE THREAD

**Issue by Papaya-Voldemort** [skbidisigma1/stocks-sim#3]
BLOCKED SITE ALERT:
![Screenshot 2024-10-30 3 01 31 PM](https://github.com/user-attachments/assets/a9342dad-0311-4eff-8323-2444b8ca45a6)

**Comment by skbidisigma1** [comment]
Yeah I'm working on this, google is really strict with their phishing detection I'm looking for a fix

**Comment by Papaya-Voldemort** [comment]
I got it removed for me at least, the sign in/sign up page looks good, maybe allow people to sign up? It needs a little more work but I know it can be done!

**Comment by skbidisigma1** [comment]
Ok I think it is fixed then! And we won't need a sign up because it uses google account. We just need to implement the password page I think @Bananaboy14 can do that later?

**Comment by Papaya-Voldemort** [comment]
k

**Comment by Papaya-Voldemort** [comment]
Hey, I found something that may help with sign up, try using auth0 (It has google log in/sign up) it may be better, also we need to find a way to store data like maybe firebase?

**Comment by skbidisigma1** [comment]
Yeah im waiting on bananyboy for this, he should be able to improve the login thing today, as he has the code for it. And firebase sounds like a good idea

**Comment by skbidisigma1** [comment]
Alright login is done for now
